server {
    listen 80;
    listen [::]:80;
    server_name ducle.uk;

    root /opt/ducle.uk;
    index index.html;

    access_log /var/log/nginx/ducle.uk.access.log;
    error_log /var/log/nginx/ducle.uk.error.log;

    location / {
        try_files $uri $uri/ =404;
    }
}
